# Uncomment this line to define a global platform for your project
#platform :tvos, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TinderTVTest' do

pod "pop", :git => 'https://github.com/facebook/pop.git', :tag => '1.0.9'
pod 'AlamofireImage', '~> 2.0'

end
